
main:main.c
	gcc -g -o main main.c
normalfunc:normalfunc.c
	gcc -g -o normalfunc normalfunc.c
errorfunc:errorfunc.c
	gcc -g -o errorfunc errorfunc.c
homework:homework.c
	gcc -g -o homework homework.c
